### ISSUE TITLE
Golden Sun layering issue

### ISSUE THREAD

**Issue by fleroviux** [jsmolka/eggvance#3]
[Golden.Sun.USA.Europe (1).zip](https://github.com/jsmolka/eggvance/files/4755450/Golden.Sun.USA.Europe.1.zip)
![image](https://user-images.githubusercontent.com/13669774/84211999-f806f300-aabc-11ea-8b2b-931d5795d1a5.png)
the carpet is occluding the character sprites, which obviously shouldn't happen.
Golden Sun makes clever usage of OBJ rendering behavior, that isn't properly documented in GBATEK.
It uses transparent OBJs to hijack the priority of the character OBJs.

This works because:
1. OBJs are rendered in forward order
2. higher priority OBJ pixels always update the OBJ buffer priority, even if the pixel transparent.
3. lower priority OBJ pixels always write the OBJ buffer if it's currently transparent.

save file is courtesy of benderscuffy.

**Comment by jsmolka** [comment]
Special thanks for this one. I had a similar issue with a piranha plant not appearing in SMB3 because its priority was messed up but I haven't had the time to investigate it further :)
